# Generated by Django 5.1.3 on 2024-11-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/photo-image/broken-image-yqwggbcj8soxi4blx8k2di.png/broken-image-0hrbdnmxhic4dti6bv0wu57.png?_a=DAJFJtWIZAAC', upload_to=''),
        ),
    ]
