# Generated by Django 5.1.3 on 2024-11-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_technology_project_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technology',
            new_name='technologies',
        ),
    ]
